#!/bin/sh
# Run by github/github codespaces after starting

echo "Starting codespace customization!"

echo "Copying dotfiles.."
cp .tmux.conf ~/
cp .gitconfig ~/

echo "Installing amix/vimrc.."
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
ln -sf "$(pwd)/my_configs.vim" ~/.vim_runtime/my_configs.vim

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi
