#!/bin/sh
# Run by github/github codespaces after starting

echo "Starting codespace customization!"

echo "Copying dotfiles.."
cp /workspaces/.codespaces/.persistedshare/dotfiles/.tmux.conf ~/
cp /workspaces/.codespaces/.persistedshare/dotfiles/.vimrc ~/
cp /workspaces/.codespaces/.persistedshare/dotfiles/.gitconfig ~/

echo "Installing vim pathogen.."
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi
