#!/bin/sh
# Run by github/github codespaces after starting

echo "Starting codespace customization!"

echo "Copying dotfiles.."
touch ~/it_worked_lq
cp /workspaces/.codespaces/.persistedshare/dotfiles/.tmux.conf ~/

# Always want to use ZSH as my default shell (e.g. for SSH)
if ! grep -q "root.*/bin/zsh" /etc/passwd
then
  chsh -s /bin/zsh root
fi

# Install some developer tools and setup Linux how I like it
apt-get install -y \
  ripgrep zsh-autosuggestions
